let btn1 = document.querySelector(".btn1")
let btn2 = document.querySelector(".btn2")
let btn3 = document.querySelector(".btn3")
let btn4 = document.querySelector(".btn4")
let btn1C = document.querySelector(".btn1C")
let btn2C = document.querySelector(".btn2C")
let btn3C = document.querySelector(".btn3C")
let btn4C = document.querySelector(".btn4C")
btn1.addEventListener("click", () => {
    btn1.classList.add("border")
    btn1.classList.remove("iBorder")
    btn2.classList.add("iBorder")
    btn3.classList.add("iBorder")
    btn4.classList.add("iBorder")
    btn1C.classList.remove("d-none")
    btn2C.classList.add("d-none")
    btn3C.classList.add("d-none")
    btn4C.classList.add("d-none")
})

btn2.addEventListener("click", () => {
    btn2.classList.add("border")
    btn2.classList.remove("iBorder")
    btn1.classList.add("iBorder")
    btn3.classList.add("iBorder")
    btn4.classList.add("iBorder")
    btn2C.classList.remove("d-none")
    btn1C.classList.add("d-none")
    btn3C.classList.add("d-none")
    btn4C.classList.add("d-none")
})

btn3.addEventListener("click", () => {
    btn3.classList.add("border")
    btn3.classList.remove("iBorder")
    btn2.classList.add("iBorder")
    btn1.classList.add("iBorder")
    btn4.classList.add("iBorder")
    btn3C.classList.remove("d-none")
    btn2C.classList.add("d-none")
    btn1C.classList.add("d-none")
    btn4C.classList.add("d-none")
})

btn4.addEventListener("click", () => {
    btn4.classList.add("border")
    btn4.classList.remove("iBorder")
    btn2.classList.add("iBorder")
    btn3.classList.add("iBorder")
    btn1.classList.add("iBorder")
    btn4C.classList.remove("d-none")
    btn2C.classList.add("d-none")
    btn1C.classList.add("d-none")
    btn3C.classList.add("d-none")
})
